name: beatarena

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: beatarena-backend
    container_name: beatarena-backend
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    environment:
      APP_NAME: BeatArena
      APP_ENV: local
      APP_KEY: base64:4VcdFbbv6vACkNs5lSV/QX7cWX23FBvlSx9jEVOTdJo=
      APP_DEBUG: true
      APP_URL: http://localhost:8787
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: beatarena
      DB_USERNAME: root
      DB_PASSWORD: password
    depends_on:
      - db
    networks:
      - beatarena-network
    command: sh -c "composer install && php artisan storage:link --force && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - "8787:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: beatarena-frontend
    container_name: beatarena-frontend
    restart: unless-stopped
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8787
    ports:
      - "3030:3000"
    depends_on:
      - backend
    networks:
      - beatarena-network

  db:
    image: mysql:8.0
    container_name: beatarena-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: beatarena
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3308:3306"
    networks:
      - beatarena-network

networks:
  beatarena-network:
    driver: bridge

volumes:
  dbdata:
